/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*******************************************************************************
 *   
 *   Copyright (C) 2015 Mytech Ingenieria Aplicada <http://www.mytechia.com>
 *   Copyright (C) 2015 Gervasio Varela <gervarela@picandocodigo.com>
 * 
 *   This file is part of Dandelion.
 *
 *   Dandelion is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   Dandelion is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with Dandelion.  If not, see <http://www.gnu.org/licenses/>.
 * 
 ******************************************************************************/
 
 package com.hi3project.dandelion.tools.specbuilder.gui;

/**
 *
 * @author Gervasio Varela <gervasio.varela@udc.es>
 */
public class EnvironmentProfilePanel extends javax.swing.JPanel
{

    /**
     * Creates new form UserProfilePanel
     */
    public EnvironmentProfilePanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        userDataPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblEnvType = new javax.swing.JLabel();
        comboEnvType = new javax.swing.JComboBox();
        lblSituation = new javax.swing.JLabel();
        comboSituation = new javax.swing.JComboBox();
        userMotionPanel = new javax.swing.JPanel();
        lblMotion = new javax.swing.JLabel();
        txtMotion = new javax.swing.JTextField();
        lblVibration = new javax.swing.JLabel();
        txtVibration = new javax.swing.JTextField();
        userClimatePanel = new javax.swing.JPanel();
        lblTemp = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        lblHumidity = new javax.swing.JLabel();
        txtHumidity = new javax.swing.JTextField();
        lblWind = new javax.swing.JLabel();
        txtWind = new javax.swing.JTextField();
        userNoisePanel = new javax.swing.JPanel();
        lblNoise = new javax.swing.JLabel();
        txtNoise = new javax.swing.JTextField();
        envSpacePanel = new javax.swing.JPanel();
        lblNoise1 = new javax.swing.JLabel();
        txtSpace = new javax.swing.JTextField();
        userVisionProfile = new javax.swing.JPanel();
        lblVisibility1 = new javax.swing.JLabel();
        txtVisibility1 = new javax.swing.JTextField();
        lblContrast1 = new javax.swing.JLabel();
        txtContrast1 = new javax.swing.JTextField();
        lblLighting1 = new javax.swing.JLabel();
        txtLighting1 = new javax.swing.JTextField();
        lblLightType1 = new javax.swing.JLabel();
        comboLight = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        userDataPanel.setLayout(new java.awt.GridLayout(4, 2));

        lblName.setText("Name");
        userDataPanel.add(lblName);

        txtName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName.setText("environment 1");
        txtName.setPreferredSize(new java.awt.Dimension(100, 28));
        userDataPanel.add(txtName);

        lblLocation.setText("Location");
        userDataPanel.add(lblLocation);

        txtLocation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLocation.setText("location 1");
        txtLocation.setPreferredSize(new java.awt.Dimension(100, 28));
        userDataPanel.add(txtLocation);

        lblEnvType.setText("Type");
        userDataPanel.add(lblEnvType);

        comboEnvType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MOBILE", "STATIONARY" }));
        userDataPanel.add(comboEnvType);

        lblSituation.setText("Situation");
        userDataPanel.add(lblSituation);

        comboSituation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INDOOR", "OUTDOOR" }));
        userDataPanel.add(comboSituation);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(userDataPanel, gridBagConstraints);

        userMotionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Motion"));
        userMotionPanel.setLayout(new java.awt.GridLayout(2, 2));

        lblMotion.setText("Motion");
        userMotionPanel.add(lblMotion);

        txtMotion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMotion.setText("0.0");
        txtMotion.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotionPanel.add(txtMotion);

        lblVibration.setText("Vibration");
        userMotionPanel.add(lblVibration);

        txtVibration.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVibration.setText("0.0");
        txtVibration.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotionPanel.add(txtVibration);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userMotionPanel, gridBagConstraints);

        userClimatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Climate"));
        userClimatePanel.setLayout(new java.awt.GridLayout(3, 2));

        lblTemp.setText("Temperature");
        userClimatePanel.add(lblTemp);

        txtTemp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTemp.setText("0.0");
        txtTemp.setPreferredSize(new java.awt.Dimension(50, 28));
        userClimatePanel.add(txtTemp);

        lblHumidity.setText("Humidity");
        userClimatePanel.add(lblHumidity);

        txtHumidity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHumidity.setText("0.0");
        txtHumidity.setPreferredSize(new java.awt.Dimension(50, 28));
        userClimatePanel.add(txtHumidity);

        lblWind.setText("Wind");
        userClimatePanel.add(lblWind);

        txtWind.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWind.setText("0.0");
        txtWind.setPreferredSize(new java.awt.Dimension(50, 28));
        userClimatePanel.add(txtWind);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userClimatePanel, gridBagConstraints);

        userNoisePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Noise"));
        userNoisePanel.setLayout(new java.awt.GridLayout(1, 2));

        lblNoise.setText("Ambient Noise");
        userNoisePanel.add(lblNoise);

        txtNoise.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNoise.setText("0.0");
        txtNoise.setPreferredSize(new java.awt.Dimension(50, 28));
        userNoisePanel.add(txtNoise);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(userNoisePanel, gridBagConstraints);

        envSpacePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Space"));
        envSpacePanel.setLayout(new java.awt.GridLayout(1, 2));

        lblNoise1.setText("Space");
        envSpacePanel.add(lblNoise1);

        txtSpace.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSpace.setText("0.0");
        txtSpace.setPreferredSize(new java.awt.Dimension(50, 28));
        envSpacePanel.add(txtSpace);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(envSpacePanel, gridBagConstraints);

        userVisionProfile.setBorder(javax.swing.BorderFactory.createTitledBorder("Visibility"));
        userVisionProfile.setLayout(new java.awt.GridLayout(4, 2));

        lblVisibility1.setText("Visibility");
        userVisionProfile.add(lblVisibility1);

        txtVisibility1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVisibility1.setText("0.0");
        txtVisibility1.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionProfile.add(txtVisibility1);

        lblContrast1.setText("Contrast");
        userVisionProfile.add(lblContrast1);

        txtContrast1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContrast1.setText("0.0");
        txtContrast1.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionProfile.add(txtContrast1);

        lblLighting1.setText("Lighting");
        userVisionProfile.add(lblLighting1);

        txtLighting1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLighting1.setText("0.0");
        txtLighting1.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionProfile.add(txtLighting1);

        lblLightType1.setText("Light Type");
        userVisionProfile.add(lblLightType1);

        comboLight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUNLIGHT", "WARMLIGHT", "COLDLIGHT", "SHADOW", "NO_LIGHT" }));
        comboLight.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionProfile.add(comboLight);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userVisionProfile, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox comboEnvType;
    public javax.swing.JComboBox comboLight;
    public javax.swing.JComboBox comboSituation;
    private javax.swing.JPanel envSpacePanel;
    private javax.swing.JLabel lblContrast1;
    private javax.swing.JLabel lblEnvType;
    private javax.swing.JLabel lblHumidity;
    private javax.swing.JLabel lblLightType1;
    private javax.swing.JLabel lblLighting1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMotion;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoise;
    private javax.swing.JLabel lblNoise1;
    private javax.swing.JLabel lblSituation;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblVibration;
    private javax.swing.JLabel lblVisibility1;
    private javax.swing.JLabel lblWind;
    public javax.swing.JTextField txtContrast1;
    public javax.swing.JTextField txtHumidity;
    public javax.swing.JTextField txtLighting1;
    public javax.swing.JTextField txtLocation;
    public javax.swing.JTextField txtMotion;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtNoise;
    public javax.swing.JTextField txtSpace;
    public javax.swing.JTextField txtTemp;
    public javax.swing.JTextField txtVibration;
    public javax.swing.JTextField txtVisibility1;
    public javax.swing.JTextField txtWind;
    private javax.swing.JPanel userClimatePanel;
    private javax.swing.JPanel userDataPanel;
    private javax.swing.JPanel userMotionPanel;
    private javax.swing.JPanel userNoisePanel;
    private javax.swing.JPanel userVisionProfile;
    // End of variables declaration//GEN-END:variables
}
