/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*******************************************************************************
 *   
 *   Copyright (C) 2015 Mytech Ingenieria Aplicada <http://www.mytechia.com>
 *   Copyright (C) 2015 Gervasio Varela <gervarela@picandocodigo.com>
 * 
 *   This file is part of Dandelion.
 *
 *   Dandelion is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   Dandelion is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with Dandelion.  If not, see <http://www.gnu.org/licenses/>.
 * 
 ******************************************************************************/
 
 package com.hi3project.dandelion.tools.specbuilder.gui;

/**
 *
 * @author Gervasio Varela <gervasio.varela@udc.es>
 */
public class FIOSpecificationPanel extends javax.swing.JPanel
{

    /**
     * Creates new form UserProfilePanel
     */
    public FIOSpecificationPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        fioPhysicalPanel = new javax.swing.JPanel();
        lblSize = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblDistance = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        fioShapePanel = new javax.swing.JPanel();
        lblShapeButton = new javax.swing.JLabel();
        txtShapeButton = new javax.swing.JTextField();
        lblShapeCustom = new javax.swing.JLabel();
        txtShapeCustom = new javax.swing.JTextField();
        lblShapeDisplay = new javax.swing.JLabel();
        txtShapeDisplay = new javax.swing.JTextField();
        lblShapeEmbedded = new javax.swing.JLabel();
        txtShapeEmbedded = new javax.swing.JTextField();
        lblShapeKeyboard = new javax.swing.JLabel();
        txtShapeKeyboard = new javax.swing.JTextField();
        lblShapeRemote = new javax.swing.JLabel();
        txtShapeRemote = new javax.swing.JTextField();
        lblShapeSurface = new javax.swing.JLabel();
        txtShapeSurface = new javax.swing.JTextField();
        lblShapeTable = new javax.swing.JLabel();
        txtShapeTable = new javax.swing.JTextField();
        lblShapeToy = new javax.swing.JLabel();
        txtShapeToy = new javax.swing.JTextField();
        lblShapeUnknown = new javax.swing.JLabel();
        txtShapeUnknown = new javax.swing.JTextField();
        fioUsagePanel = new javax.swing.JPanel();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblICTLiteracy = new javax.swing.JLabel();
        txtICTLiteracy = new javax.swing.JTextField();
        fioModalitiesPanel = new javax.swing.JPanel();
        lblShapeButton1 = new javax.swing.JLabel();
        txtModGesture = new javax.swing.JTextField();
        lblShapeCustom1 = new javax.swing.JLabel();
        txtModKeyboard = new javax.swing.JTextField();
        lblShapeDisplay2 = new javax.swing.JLabel();
        txtModSoundProd = new javax.swing.JTextField();
        lblShapeEmbedded1 = new javax.swing.JLabel();
        txtModSpeech = new javax.swing.JTextField();
        lblShapeEmbedded2 = new javax.swing.JLabel();
        txtModSpeechProd = new javax.swing.JTextField();
        lblShapeKeyboard1 = new javax.swing.JLabel();
        txtModSymbol = new javax.swing.JTextField();
        lblShapeRemote1 = new javax.swing.JLabel();
        txtModTouch = new javax.swing.JTextField();
        lblShapeSurface1 = new javax.swing.JLabel();
        txtModWimp = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        fioPhysicalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical"));
        fioPhysicalPanel.setLayout(new java.awt.GridLayout(3, 2));

        lblSize.setText("Size");
        fioPhysicalPanel.add(lblSize);

        txtSize.setEditable(false);
        txtSize.setBackground(new java.awt.Color(250, 248, 225));
        txtSize.setForeground(new java.awt.Color(0, 0, 255));
        txtSize.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSize.setText("0.0");
        txtSize.setPreferredSize(new java.awt.Dimension(50, 28));
        fioPhysicalPanel.add(txtSize);

        lblStatus.setText("Status");
        fioPhysicalPanel.add(lblStatus);

        txtStatus.setEditable(false);
        txtStatus.setBackground(new java.awt.Color(250, 248, 225));
        txtStatus.setForeground(new java.awt.Color(0, 0, 255));
        txtStatus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtStatus.setText("0.0");
        txtStatus.setPreferredSize(new java.awt.Dimension(50, 28));
        fioPhysicalPanel.add(txtStatus);

        lblDistance.setText("Distance");
        fioPhysicalPanel.add(lblDistance);

        txtDistance.setEditable(false);
        txtDistance.setBackground(new java.awt.Color(250, 248, 225));
        txtDistance.setForeground(new java.awt.Color(0, 0, 255));
        txtDistance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDistance.setText("0.0");
        txtDistance.setPreferredSize(new java.awt.Dimension(50, 28));
        fioPhysicalPanel.add(txtDistance);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(fioPhysicalPanel, gridBagConstraints);

        fioShapePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Shape"));
        fioShapePanel.setLayout(new java.awt.GridLayout(10, 2));

        lblShapeButton.setText("Button");
        fioShapePanel.add(lblShapeButton);

        txtShapeButton.setEditable(false);
        txtShapeButton.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeButton.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeButton.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeButton.setText("0.0");
        txtShapeButton.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeButton);

        lblShapeCustom.setText("Custom");
        fioShapePanel.add(lblShapeCustom);

        txtShapeCustom.setEditable(false);
        txtShapeCustom.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeCustom.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeCustom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeCustom.setText("0.0");
        txtShapeCustom.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeCustom);

        lblShapeDisplay.setText("Display");
        fioShapePanel.add(lblShapeDisplay);

        txtShapeDisplay.setEditable(false);
        txtShapeDisplay.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeDisplay.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeDisplay.setText("0.0");
        txtShapeDisplay.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeDisplay);

        lblShapeEmbedded.setText("Embedded");
        fioShapePanel.add(lblShapeEmbedded);

        txtShapeEmbedded.setEditable(false);
        txtShapeEmbedded.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeEmbedded.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeEmbedded.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeEmbedded.setText("0.0");
        txtShapeEmbedded.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeEmbedded);

        lblShapeKeyboard.setText("Keyboard");
        fioShapePanel.add(lblShapeKeyboard);

        txtShapeKeyboard.setEditable(false);
        txtShapeKeyboard.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeKeyboard.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeKeyboard.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeKeyboard.setText("0.0");
        txtShapeKeyboard.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeKeyboard);

        lblShapeRemote.setText("Remote");
        fioShapePanel.add(lblShapeRemote);

        txtShapeRemote.setEditable(false);
        txtShapeRemote.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeRemote.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeRemote.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeRemote.setText("0.0");
        txtShapeRemote.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeRemote);

        lblShapeSurface.setText("Surface");
        fioShapePanel.add(lblShapeSurface);

        txtShapeSurface.setEditable(false);
        txtShapeSurface.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeSurface.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeSurface.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeSurface.setText("0.0");
        txtShapeSurface.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeSurface);

        lblShapeTable.setText("Table");
        fioShapePanel.add(lblShapeTable);

        txtShapeTable.setEditable(false);
        txtShapeTable.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeTable.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeTable.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeTable.setText("0.0");
        txtShapeTable.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeTable);

        lblShapeToy.setText("Toy");
        fioShapePanel.add(lblShapeToy);

        txtShapeToy.setEditable(false);
        txtShapeToy.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeToy.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeToy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeToy.setText("0.0");
        txtShapeToy.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeToy);

        lblShapeUnknown.setText("Unknown");
        fioShapePanel.add(lblShapeUnknown);

        txtShapeUnknown.setEditable(false);
        txtShapeUnknown.setBackground(new java.awt.Color(250, 248, 225));
        txtShapeUnknown.setForeground(new java.awt.Color(0, 0, 255));
        txtShapeUnknown.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShapeUnknown.setText("0.0");
        txtShapeUnknown.setPreferredSize(new java.awt.Dimension(50, 28));
        fioShapePanel.add(txtShapeUnknown);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(fioShapePanel, gridBagConstraints);

        fioUsagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Usage"));
        fioUsagePanel.setLayout(new java.awt.GridLayout(2, 2));

        lblAge.setText("Recom. Age");
        fioUsagePanel.add(lblAge);

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(250, 248, 225));
        txtAge.setForeground(new java.awt.Color(0, 0, 255));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAge.setText("0.0");
        txtAge.setPreferredSize(new java.awt.Dimension(50, 28));
        fioUsagePanel.add(txtAge);

        lblICTLiteracy.setText("ICT Literacy");
        fioUsagePanel.add(lblICTLiteracy);

        txtICTLiteracy.setEditable(false);
        txtICTLiteracy.setBackground(new java.awt.Color(250, 248, 225));
        txtICTLiteracy.setForeground(new java.awt.Color(0, 0, 255));
        txtICTLiteracy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtICTLiteracy.setText("0.0");
        txtICTLiteracy.setPreferredSize(new java.awt.Dimension(50, 28));
        fioUsagePanel.add(txtICTLiteracy);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(fioUsagePanel, gridBagConstraints);

        fioModalitiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Modality"));
        fioModalitiesPanel.setLayout(new java.awt.GridLayout(8, 2));

        lblShapeButton1.setText("Gesture");
        fioModalitiesPanel.add(lblShapeButton1);

        txtModGesture.setEditable(false);
        txtModGesture.setBackground(new java.awt.Color(250, 248, 225));
        txtModGesture.setForeground(new java.awt.Color(0, 0, 255));
        txtModGesture.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModGesture.setText("0.0");
        txtModGesture.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModGesture);

        lblShapeCustom1.setText("Keyboard");
        fioModalitiesPanel.add(lblShapeCustom1);

        txtModKeyboard.setEditable(false);
        txtModKeyboard.setBackground(new java.awt.Color(250, 248, 225));
        txtModKeyboard.setForeground(new java.awt.Color(0, 0, 255));
        txtModKeyboard.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModKeyboard.setText("0.0");
        txtModKeyboard.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModKeyboard);

        lblShapeDisplay2.setText("Sound Prod.");
        lblShapeDisplay2.setToolTipText("");
        fioModalitiesPanel.add(lblShapeDisplay2);

        txtModSoundProd.setEditable(false);
        txtModSoundProd.setBackground(new java.awt.Color(250, 248, 225));
        txtModSoundProd.setForeground(new java.awt.Color(0, 0, 255));
        txtModSoundProd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModSoundProd.setText("0.0");
        txtModSoundProd.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModSoundProd);

        lblShapeEmbedded1.setText("Speech Recog.");
        fioModalitiesPanel.add(lblShapeEmbedded1);

        txtModSpeech.setEditable(false);
        txtModSpeech.setBackground(new java.awt.Color(250, 248, 225));
        txtModSpeech.setForeground(new java.awt.Color(0, 0, 255));
        txtModSpeech.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModSpeech.setText("0.0");
        txtModSpeech.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModSpeech);

        lblShapeEmbedded2.setText("Speech Prod.");
        fioModalitiesPanel.add(lblShapeEmbedded2);

        txtModSpeechProd.setEditable(false);
        txtModSpeechProd.setBackground(new java.awt.Color(250, 248, 225));
        txtModSpeechProd.setForeground(new java.awt.Color(0, 0, 255));
        txtModSpeechProd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModSpeechProd.setText("0.0");
        txtModSpeechProd.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModSpeechProd);

        lblShapeKeyboard1.setText("Symbol");
        fioModalitiesPanel.add(lblShapeKeyboard1);

        txtModSymbol.setEditable(false);
        txtModSymbol.setBackground(new java.awt.Color(250, 248, 225));
        txtModSymbol.setForeground(new java.awt.Color(0, 0, 255));
        txtModSymbol.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModSymbol.setText("0.0");
        txtModSymbol.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModSymbol);

        lblShapeRemote1.setText("Touch");
        fioModalitiesPanel.add(lblShapeRemote1);

        txtModTouch.setEditable(false);
        txtModTouch.setBackground(new java.awt.Color(250, 248, 225));
        txtModTouch.setForeground(new java.awt.Color(0, 0, 255));
        txtModTouch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModTouch.setText("0.0");
        txtModTouch.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModTouch);

        lblShapeSurface1.setText("WIMP");
        fioModalitiesPanel.add(lblShapeSurface1);

        txtModWimp.setEditable(false);
        txtModWimp.setBackground(new java.awt.Color(250, 248, 225));
        txtModWimp.setForeground(new java.awt.Color(0, 0, 255));
        txtModWimp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModWimp.setText("0.0");
        txtModWimp.setPreferredSize(new java.awt.Dimension(50, 28));
        fioModalitiesPanel.add(txtModWimp);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(fioModalitiesPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fioModalitiesPanel;
    private javax.swing.JPanel fioPhysicalPanel;
    private javax.swing.JPanel fioShapePanel;
    private javax.swing.JPanel fioUsagePanel;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblICTLiteracy;
    private javax.swing.JLabel lblShapeButton;
    private javax.swing.JLabel lblShapeButton1;
    private javax.swing.JLabel lblShapeCustom;
    private javax.swing.JLabel lblShapeCustom1;
    private javax.swing.JLabel lblShapeDisplay;
    private javax.swing.JLabel lblShapeDisplay2;
    private javax.swing.JLabel lblShapeEmbedded;
    private javax.swing.JLabel lblShapeEmbedded1;
    private javax.swing.JLabel lblShapeEmbedded2;
    private javax.swing.JLabel lblShapeKeyboard;
    private javax.swing.JLabel lblShapeKeyboard1;
    private javax.swing.JLabel lblShapeRemote;
    private javax.swing.JLabel lblShapeRemote1;
    private javax.swing.JLabel lblShapeSurface;
    private javax.swing.JLabel lblShapeSurface1;
    private javax.swing.JLabel lblShapeTable;
    private javax.swing.JLabel lblShapeToy;
    private javax.swing.JLabel lblShapeUnknown;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblStatus;
    public javax.swing.JTextField txtAge;
    public javax.swing.JTextField txtDistance;
    public javax.swing.JTextField txtICTLiteracy;
    public javax.swing.JTextField txtModGesture;
    public javax.swing.JTextField txtModKeyboard;
    public javax.swing.JTextField txtModSoundProd;
    public javax.swing.JTextField txtModSpeech;
    public javax.swing.JTextField txtModSpeechProd;
    public javax.swing.JTextField txtModSymbol;
    public javax.swing.JTextField txtModTouch;
    public javax.swing.JTextField txtModWimp;
    public javax.swing.JTextField txtShapeButton;
    public javax.swing.JTextField txtShapeCustom;
    public javax.swing.JTextField txtShapeDisplay;
    public javax.swing.JTextField txtShapeEmbedded;
    public javax.swing.JTextField txtShapeKeyboard;
    public javax.swing.JTextField txtShapeRemote;
    public javax.swing.JTextField txtShapeSurface;
    public javax.swing.JTextField txtShapeTable;
    public javax.swing.JTextField txtShapeToy;
    public javax.swing.JTextField txtShapeUnknown;
    public javax.swing.JTextField txtSize;
    public javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
