/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*******************************************************************************
 *   
 *   Copyright (C) 2015 Mytech Ingenieria Aplicada <http://www.mytechia.com>
 *   Copyright (C) 2015 Gervasio Varela <gervarela@picandocodigo.com>
 * 
 *   This file is part of Dandelion.
 *
 *   Dandelion is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   Dandelion is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with Dandelion.  If not, see <http://www.gnu.org/licenses/>.
 * 
 ******************************************************************************/
 
 package com.hi3project.dandelion.tools.specbuilder.gui;

/**
 *
 * @author Gervasio Varela <gervasio.varela@udc.es>
 */
public class UserProfilePanel extends javax.swing.JPanel
{

    /**
     * Creates new form UserProfilePanel
     */
    public UserProfilePanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        userDataPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        userHearingPanel = new javax.swing.JPanel();
        lblHearing = new javax.swing.JLabel();
        txtHearing = new javax.swing.JTextField();
        userICTPanel = new javax.swing.JPanel();
        lblLiteracy = new javax.swing.JLabel();
        txtLiteracy = new javax.swing.JTextField();
        lblAnxiety = new javax.swing.JLabel();
        txtAnxiety = new javax.swing.JTextField();
        userVisionPanel = new javax.swing.JPanel();
        lblAcuity = new javax.swing.JLabel();
        txtAcuity = new javax.swing.JTextField();
        lblField = new javax.swing.JLabel();
        txtField = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        comboColor = new javax.swing.JComboBox();
        userMotorPanel = new javax.swing.JPanel();
        lblSpeechArtic = new javax.swing.JLabel();
        txtSpeechArtic = new javax.swing.JTextField();
        lblFinger = new javax.swing.JLabel();
        txtFinger = new javax.swing.JTextField();
        lblHand = new javax.swing.JLabel();
        txtHand = new javax.swing.JTextField();
        lblArm = new javax.swing.JLabel();
        txtArm = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblPinch = new javax.swing.JLabel();
        txtPinch = new javax.swing.JTextField();
        lblClench = new javax.swing.JLabel();
        txtClench = new javax.swing.JTextField();
        lblHandEye = new javax.swing.JLabel();
        txtHandEye = new javax.swing.JTextField();
        userCognitivePanel = new javax.swing.JPanel();
        lblLangRecept = new javax.swing.JLabel();
        txtLangRecept = new javax.swing.JTextField();
        lblLangProd = new javax.swing.JLabel();
        txtLangProd = new javax.swing.JTextField();
        lblSigns = new javax.swing.JLabel();
        txtSigns = new javax.swing.JTextField();
        lblAttention = new javax.swing.JLabel();
        txtAttention = new javax.swing.JTextField();
        lblProcSpeed = new javax.swing.JLabel();
        txtProcSpeed = new javax.swing.JTextField();
        lblWorkMem = new javax.swing.JLabel();
        txtWorkMem = new javax.swing.JTextField();
        lblLongMem = new javax.swing.JLabel();
        txtLongMem = new javax.swing.JTextField();
        userPhysicalPanel = new javax.swing.JPanel();
        lblHeight = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        userDataPanel.setLayout(new java.awt.GridBagLayout());

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        userDataPanel.add(lblName, gridBagConstraints);

        txtName.setText("name surname...");
        txtName.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        userDataPanel.add(txtName, gridBagConstraints);

        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAge.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        userDataPanel.add(lblAge, gridBagConstraints);

        txtAge.setText("25");
        txtAge.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        userDataPanel.add(txtAge, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userDataPanel, gridBagConstraints);

        userHearingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hearing"));
        userHearingPanel.setLayout(new java.awt.GridLayout(1, 2));

        lblHearing.setText("Acuity");
        userHearingPanel.add(lblHearing);

        txtHearing.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHearing.setText("0.0");
        txtHearing.setPreferredSize(new java.awt.Dimension(50, 28));
        userHearingPanel.add(txtHearing);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userHearingPanel, gridBagConstraints);

        userICTPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("ICT"));
        userICTPanel.setLayout(new java.awt.GridLayout(2, 2));

        lblLiteracy.setText("Literacy");
        userICTPanel.add(lblLiteracy);

        txtLiteracy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLiteracy.setText("0.0");
        txtLiteracy.setPreferredSize(new java.awt.Dimension(50, 28));
        userICTPanel.add(txtLiteracy);

        lblAnxiety.setText("Anxiety");
        userICTPanel.add(lblAnxiety);

        txtAnxiety.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAnxiety.setText("0.0");
        txtAnxiety.setPreferredSize(new java.awt.Dimension(50, 28));
        userICTPanel.add(txtAnxiety);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userICTPanel, gridBagConstraints);

        userVisionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vision"));
        userVisionPanel.setLayout(new java.awt.GridLayout(3, 2));

        lblAcuity.setText("Acuity");
        userVisionPanel.add(lblAcuity);

        txtAcuity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAcuity.setText("0.0");
        txtAcuity.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionPanel.add(txtAcuity);

        lblField.setText("Field");
        userVisionPanel.add(lblField);

        txtField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtField.setText("0.0");
        txtField.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionPanel.add(txtField);

        lblColor.setText("Color ");
        userVisionPanel.add(lblColor);

        comboColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FULL_COLOR", "COLOR_BLIND" }));
        comboColor.setPreferredSize(new java.awt.Dimension(50, 28));
        userVisionPanel.add(comboColor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userVisionPanel, gridBagConstraints);

        userMotorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Motor"));
        userMotorPanel.setLayout(new java.awt.GridLayout(8, 2));

        lblSpeechArtic.setText("Speech Artic.");
        userMotorPanel.add(lblSpeechArtic);

        txtSpeechArtic.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSpeechArtic.setText("0.0");
        txtSpeechArtic.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtSpeechArtic);

        lblFinger.setText("Finger Precis.");
        userMotorPanel.add(lblFinger);

        txtFinger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFinger.setText("0.0");
        txtFinger.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtFinger);

        lblHand.setText("Hand Precis.");
        userMotorPanel.add(lblHand);

        txtHand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHand.setText("0.0");
        txtHand.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtHand);

        lblArm.setText("Arm Precis.");
        userMotorPanel.add(lblArm);

        txtArm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArm.setText("0.0");
        txtArm.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtArm);

        lblContact.setText("Contact Grip");
        userMotorPanel.add(lblContact);

        txtContact.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContact.setText("0.0");
        txtContact.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtContact);

        lblPinch.setText("Pinch Grip");
        userMotorPanel.add(lblPinch);

        txtPinch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPinch.setText("0.0");
        txtPinch.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtPinch);

        lblClench.setText("Clench Grip");
        userMotorPanel.add(lblClench);

        txtClench.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClench.setText("0.0");
        txtClench.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtClench);

        lblHandEye.setText("Hand-Eye");
        userMotorPanel.add(lblHandEye);

        txtHandEye.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHandEye.setText("0.0");
        txtHandEye.setPreferredSize(new java.awt.Dimension(50, 28));
        userMotorPanel.add(txtHandEye);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userMotorPanel, gridBagConstraints);

        userCognitivePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cognitive"));
        userCognitivePanel.setLayout(new java.awt.GridLayout(7, 2));

        lblLangRecept.setText("Lang. Recept.");
        userCognitivePanel.add(lblLangRecept);

        txtLangRecept.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLangRecept.setText("0.0");
        txtLangRecept.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtLangRecept);

        lblLangProd.setText("Lang. Prod.");
        userCognitivePanel.add(lblLangProd);

        txtLangProd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLangProd.setText("0.0");
        txtLangProd.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtLangProd);

        lblSigns.setText("Abs. Signs");
        userCognitivePanel.add(lblSigns);

        txtSigns.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSigns.setText("0.0");
        txtSigns.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtSigns);

        lblAttention.setText("Attention");
        userCognitivePanel.add(lblAttention);

        txtAttention.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAttention.setText("0.0");
        txtAttention.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtAttention);

        lblProcSpeed.setText("Proc. Speed");
        userCognitivePanel.add(lblProcSpeed);

        txtProcSpeed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtProcSpeed.setText("0.0");
        txtProcSpeed.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtProcSpeed);

        lblWorkMem.setText("Work. Mem.");
        userCognitivePanel.add(lblWorkMem);

        txtWorkMem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWorkMem.setText("0.0");
        txtWorkMem.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtWorkMem);

        lblLongMem.setText("L. T. Mem.");
        userCognitivePanel.add(lblLongMem);

        txtLongMem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtLongMem.setText("0.0");
        txtLongMem.setPreferredSize(new java.awt.Dimension(50, 28));
        userCognitivePanel.add(txtLongMem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userCognitivePanel, gridBagConstraints);

        userPhysicalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical"));
        userPhysicalPanel.setLayout(new java.awt.GridLayout(2, 2));

        lblHeight.setText("Height");
        userPhysicalPanel.add(lblHeight);

        txtHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHeight.setText("0.0");
        txtHeight.setPreferredSize(new java.awt.Dimension(50, 28));
        userPhysicalPanel.add(txtHeight);

        lblWeight.setText("Weight");
        userPhysicalPanel.add(lblWeight);

        txtWeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWeight.setText("0.0");
        txtWeight.setMinimumSize(new java.awt.Dimension(14, 70));
        txtWeight.setPreferredSize(new java.awt.Dimension(50, 28));
        userPhysicalPanel.add(txtWeight);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userPhysicalPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox comboColor;
    private javax.swing.JLabel lblAcuity;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAnxiety;
    private javax.swing.JLabel lblArm;
    private javax.swing.JLabel lblAttention;
    private javax.swing.JLabel lblClench;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblField;
    private javax.swing.JLabel lblFinger;
    private javax.swing.JLabel lblHand;
    private javax.swing.JLabel lblHandEye;
    private javax.swing.JLabel lblHearing;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLangProd;
    private javax.swing.JLabel lblLangRecept;
    private javax.swing.JLabel lblLiteracy;
    private javax.swing.JLabel lblLongMem;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPinch;
    private javax.swing.JLabel lblProcSpeed;
    private javax.swing.JLabel lblSigns;
    private javax.swing.JLabel lblSpeechArtic;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWorkMem;
    public javax.swing.JTextField txtAcuity;
    public javax.swing.JTextField txtAge;
    public javax.swing.JTextField txtAnxiety;
    public javax.swing.JTextField txtArm;
    public javax.swing.JTextField txtAttention;
    public javax.swing.JTextField txtClench;
    public javax.swing.JTextField txtContact;
    public javax.swing.JTextField txtField;
    public javax.swing.JTextField txtFinger;
    public javax.swing.JTextField txtHand;
    public javax.swing.JTextField txtHandEye;
    public javax.swing.JTextField txtHearing;
    public javax.swing.JTextField txtHeight;
    public javax.swing.JTextField txtLangProd;
    public javax.swing.JTextField txtLangRecept;
    public javax.swing.JTextField txtLiteracy;
    public javax.swing.JTextField txtLongMem;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtPinch;
    public javax.swing.JTextField txtProcSpeed;
    public javax.swing.JTextField txtSigns;
    public javax.swing.JTextField txtSpeechArtic;
    public javax.swing.JTextField txtWeight;
    public javax.swing.JTextField txtWorkMem;
    private javax.swing.JPanel userCognitivePanel;
    private javax.swing.JPanel userDataPanel;
    private javax.swing.JPanel userHearingPanel;
    private javax.swing.JPanel userICTPanel;
    private javax.swing.JPanel userMotorPanel;
    private javax.swing.JPanel userPhysicalPanel;
    private javax.swing.JPanel userVisionPanel;
    // End of variables declaration//GEN-END:variables
}
